### PR TITLE
Add a condition to the nearest neighbor methods

### PR DESCRIPTION
**Pull request by chriseidhof**
Here's a PR with the conditional.

I'm pretty sure the `nearestK` version is correct, but Im' not sure if the `nearest` is correct, please review. What would be even better is adding tests (that's why I marked it as WIP). However, as the project is still Swift 3, the test target isn't automatically added by SPM...

### CODE REVIEW

**Comment by chriseidhof** [comment]
Ok I added three tiny tests (the nearest(K) methods weren't under test yet)

**Comment by Bersaelor** [comment]
I thought I updated it to `Swift4` in this commit: https://github.com/Bersaelor/KDTree/commit/cb620782149008861eb96a880780e96817282fe5

**Comment by chriseidhof** [comment]
I thought the project was Swift 3 because of the missing test target :p

**Comment by Bersaelor** [comment]
I have to admit, the way the project grew the tests are out of wack.
Since the xcodeproj I use for development is the one created by cocoapods in `Example/KDTree.xcworkspace/` some tests are actually duplicated between 
`Example/Tests/` and `Tests`. The former being the test-target tests associated with the cocoapods example app, the latter the KDTree tests.
I'll refactor those so they share common tests.

**Pull request merged**
